	<div id="copyright">
		<p>Copyright &copy; 2002-<script type="text/javascript">
      var d = new Date();
      document.write(d.getFullYear());
   </script>, Iron Horse Restaurant. All Rights Reserved.</p>
		<p><a href='ma&#105;&#108;to&#58;i%6&#56;%&#55;2e&#115;&#116;&#64;po%&#55;2&#116;lan&#37;64&#37;&#54;9&#114;o%&#54;E&#37;&#54;8or&#115;e&#46;co&#37;&#54;&#68;'>ihrest@portlandironhorse.com</a></p>
		<p><a href="../../SiteMap.htm">Site Map</a></p>
		<p><a href="http://www.bigbmanagedservices.com">Website Development &amp; Hosting:<br />Big B Managed Services</a></p>
	</div>
	<!-- end div COPYRIGHT -->
	<br />