   <h2>Dessert Menu</h2>
   <h3>Key Lime Pie</h3>
   <p>Sweet lime pie topped with merengue.&hellip; 5.95</p>
   <h3>Banana Cream Pie</h3>
   <p>Topped with whipped cream, caramel sauce, and shaved chocolate.&hellip; 5.95</p>
   <h3>Flan</h3>
   <p>Caramel custard served with a dollop of whipped cream.&hellip; 4.95</p>
   <h3>Coca-Cola Chocolate Cake</h3>
   <p>Double layered chocolate cake with chocolate icing and walnuts. Ala mode upon request.&hellip; 5.95</p>
   <h3>Bowl of Vanilla Ice Cream.&hellip; 3.95</h3>
   <p>Top it with chocolate sauce, strawberry, mango or raspberry puree.&hellip; 4.50</p>