   <h4>We do not use lard or any item that contains lard.<br />
      We only use olive oil and pure vegetable oils.<br />
      We only use soy based margarine<br />
      Our chips are fried in vegetable oil.<br />
      Flour tortillas contain yeast &amp; wheat, corn tortillas do not.<br />
      Our rice is made with vegetable oil.<br />
      All of our desserts contain dairy products.</h4><br />