<h2>Sides</h2>
<h3>Guacamole</h3>
<p>Small&hellip; 4.95 Large&hellip; 6.95</p>
<h3>Salsa Verde</h3>
<p>Small&hellip; .50 Large&hellip; .75</p>
<h3>Pico de gallo</h3>
<p>Small&hellip;  .72 Large&hellip; 1.50</p>
<h3>Spicy Avocado Sauce</h3>
<p>&hellip; 1.95</p>
<h3>Spanish Rice</h3>
<p>&hellip; 2.50</p>
<h3>Refried, Refried Black or Black Beans</h3>
<p>&hellip; 2.50</p>
<h3>Rice and Beans</h3>
<p>&hellip; 3.95</p>
<h3>Pickled or Fresh jalape&ntilde;os</h3>
<p>&hellip; 1.00</p>
<h3>3 Tortillas</h3>
<p>(corn or flour) 1.50</p>