<h2>Sides</h2>
<h3>Sour Cream</h3>
<p>Small&hellip; 1.00 Large&hellip; 2.00</p>
<h3>Guacamole</h3>
<p>Small&hellip; 4.95 Large&hellip; 6.95</p>
<p><span>Salsa Verde </span>Small&hellip; .50 Large&hellip; .75<br />
<span>Salsa Cecilia </span>Small&hellip; .75 Large&hellip; 1.50<br />
<span>Pico de gallo </span>Small&hellip; .75 Large&hellip; 1.50<br />
<span>Spicy Avocado Sauce </span>&hellip; 1.95<br />
<span>Spanish Rice </span>&hellip; 2.50<br />
<span>Refried, Refried Black or Black Beans </span>&hellip; 2.50<br />
<span>Rice and Beans </span>&hellip; 3.95<br />
<span>Pickled or Fresh jalape&ntilde;os </span>&hellip; 1.00<br />
<span>Yucatan Slaw </span>&hellip; 1.50<br />
<span>3 Tortillas </span> (corn) 1.50</p>