<h2 class="center">Appetizers</h2>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Guacamole:</h3>
<p>Small&hellip; 4.95 Large&hellip; 6.95</p>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Bean Dip</h3>
<p>(Please order "without cheese")<br />
A bowl of refried or black beans topped with green onions&hellip; 3.50</p>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Mini Tacos:</h3>
<p>(Please order "without cheese")<br />
Small crisp tacos filled with refried or black beans.<br />
Topped with lettuce, tomatoes, olives and green onions (3)&hellip; 5.95 (6)&hellip; 10.95</p>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Old-Style Nacho</h3>
<p>(Please order "old style nacho - without cheese")<br />
Black or refried beans topped with lettuce, chopped tomatoes, olives and green onions.<br />
Served with chips for dipping. Personal&hellip; 7.50 Large&hellip; 9.95<br />
Add guacamole 2.25</p>
<div class="break"></div>
<h2 class="center">Small Salads</h2>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Iron Horse Salad</h3>
<p>(Please order "without cheese")<br />
Mixed lettuces, tomatoes, red onion and Mexican cheese, tossed with vinaigrette&hellip; 5.50</p>
<h3>Dressing for salads below:</h3>
<p>Basalmic vinaigrette</p>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Dinner Salad</h3>
<p>(Please order basalmic vinaigrette dressing and "without cheese")<br />
Lettuce, tomatoes, olives and green onions&hellip; 5.00</p>
<h3><img src="resources/images/Flying_Tomato_Small.gif" alt="Flying tomato denotes vegetarian options." align="bottom"/> Spinach Salad</h3>
<p>(Please order basalmic vinaigrette dressing and "without cheese")<br />
Fresh spinach, red onions, tomatoes and sliced almonds&hellip; 5.00</p>