	<div id="fees">
		<h6>We do not use lard in any of our beans.</h6>
		<h6>Some of our menu items contain chocolate and/or peanuts.</h6>
		<h6>Please ask your server about menu items if you have food allergies.</h6>
		<h6>We request reservations for parties of 6 or more.</h6>
		<h6>Extra charges will apply for split plates&hellip; 2.00 and extra plate&hellip; 1.00</h6>
		<h6>All of our menu items may be ordered to go&hellip; just add .75 cents per item.</h6>
	</div>
	<!-- end div EXTRA_FEES -->
