<div id="footer">
	<p>TEL: 503-232-1826<br />6034 SE Milwaukie Ave.<br />Portland, OR 97202</p>
		<div align="center">
			<!-- Like Button Start -->
    </div>
  <div id="fb-root"></div>
    <div align="center">
      <script>(function(d){
        var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#appId=264667313557636&xfbml=1";
  d.getElementsByTagName('head')[0].appendChild(js);
}(document));</script>
           </div>
 <fb:like href="http://www.facebook.com/pages/IRON-HORSE-RESTAURANT/159541122389" send="true" layout="button_count" width="450" show_faces="true" font="tahoma"></fb:like>
           <div align="center">
             <!-- Like Button End -->
           </div>
</div>
		<!-- end div FOOTER -->