<li><a class="Home" href="/">Home</a></li>		
<li class="menus"><a>Menus</a>
  <ul class="mobile-sub-nav">
    <li><a class="Lunch_Menu" href="../../Lunch_Menu.htm">Lunch</a></li>
    <li><a class="Dinner_Menu" href="../../Dinner_Menu.htm">Dinner</a></li>
    <li><a href="../../resources/images/pdf/Specials_Calendar.pdf" target="_blank" class="specials">Specials</a></li>
    <li><a class="Happy_Hour_Menu" href="../../Happy_Hour_Menu.htm">Happy Hour</a></li>
    <li><a class="Vegetarian_Menu" href="../../Vegetarian_Menu.htm">Vegetarian</a></li>
    <li><a class="Vegan_Menu" href="../../Vegan_Menu.htm">Vegan</a></li>
    <li><a class="Gluten_Free_Menu" href="../../Gluten_Free_Menu.htm">Gluten Free</a></li>
    <li><a class="Kids_Menu" href="../../Kids_Menu.htm">Kids</a></li>
  </ul>
</li>
<li><a class="Gift_Certificates" href="../../Gift_Certificates.htm">Gift Certs</a></li>
<li><a class="Banquets" href="../../Banquet_Room.htm">Banquets</a></li>
<li><a class="Catering" href="../../Catering.htm">Catering</a></li>
<li><a class="Contact_Us" href="../../Contact_Us.htm">Contact Us</a></li>
<li><a class="MailList" href="../../Mailing_List.htm">Email List</a></li>